name: Build and deploy Aseprite

on:
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Build sekarang'
        required: false
        default: 'true'
  push:
    branches:
      - main
      - master

env:
  BUILD_TYPE: Release

jobs:
  build-aseprite:
    name: Build Aseprite (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dapatkan info rilis Aseprite terbaru
        id: latest
        shell: powershell
        run: |
          $resp = Invoke-RestMethod -Uri "https://api.github.com/repos/aseprite/aseprite/releases/latest" -Headers @{ "Accept"="application/vnd.github+json" }
          $tag = $resp.tag_name
          $src = ($resp.assets | Where-Object { $_.name -like "*-Source.zip" }).browser_download_url
          "tag=$tag" >> $env:GITHUB_OUTPUT
          "src=$src" >> $env:GITHUB_OUTPUT

      - name: Cache Skia m124
        id: skia-cache
        uses: actions/cache@v4
        with:
          path: skia
          key: skia-${{ runner.os }}-m124

      - name: Download & ekstrak Skia m124 (jika belum ada)
        if: steps.skia-cache.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          $url = "https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip"
          Invoke-WebRequest -Uri $url -OutFile skia.zip
          if (Test-Path skia) { Remove-Item -Recurse -Force skia }
          Expand-Archive -Path skia.zip -DestinationPath skia

      - name: Unduh source Aseprite
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "${{ steps.latest.outputs.src }}" -OutFile Aseprite-source.zip
          if (Test-Path aseprite) { Remove-Item -Recurse -Force aseprite }
          New-Item -ItemType Directory -Path aseprite | Out-Null
          Expand-Archive -Path Aseprite-source.zip -DestinationPath aseprite

      - name: Install Ninja (manual)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-win.zip" -OutFile ninja.zip
          Expand-Archive ninja.zip -DestinationPath $env:RUNNER_TEMP\ninja
          "$env:RUNNER_TEMP\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          ninja --version

      - name: Aktifkan Visual Studio 2022 (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Siapkan folder build
        shell: powershell
        working-directory: aseprite
        run: |
          if (!(Test-Path build)) { New-Item -ItemType Directory -Path build | Out-Null }

      - name: Konfigurasi CMake (Ninja + Skia)
        shell: cmd
        working-directory: aseprite/build
        run: >
          cmake -G Ninja
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DLAF_BACKEND=skia
          -DSKIA_DIR=../../skia
          -DSKIA_LIBRARY_DIR=../../skia/out/Release-x64
          -DSKIA_LIBRARY=../../skia/out/Release-x64/skia.lib
          ..

      - name: Build
        working-directory: aseprite/build
        run: ninja aseprite

      - name: Jadikan portable
        working-directory: aseprite/build/bin
        shell: powershell
        run: |
          '# portable' | Out-File -FilePath aseprite.ini -Encoding utf8

      - name: Kemasi ZIP
        shell: powershell
        run: |
          $zipName = "Aseprite-${{ steps.latest.outputs.tag }}-Windows-x64.zip"
          if (Test-Path $zipName) { Remove-Item $zipName -Force }
          Compress-Archive -Path "aseprite/build/bin/*" -DestinationPath $zipName

      - name: Upload ke Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: "aseprite-${{ steps.latest.outputs.tag }}-${{ github.run_id }}"
          name: "Aseprite ${{ steps.latest.outputs.tag }} (Windows x64)"
          files: |
            Aseprite-${{ steps.latest.outputs.tag }}-Windows-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
